gens_homepage:
    pattern:  /
    defaults: { _controller: GensBundle:Default:index }

gens_libro:
    pattern:  /display/{libro}/
    defaults: { _controller: GensBundle:Default:showlibro }

gens_capitulo:
    pattern:  /display/{libro}/{capitulo}
    defaults: { _controller: GensBundle:Default:showcapitulo }
    requirements:
        capitulo:  \d+

dashboard:
    pattern: /admin/dashboard/
    defaults: { _controller: GensBundle:Admin:dashboard }

crear_libro:
    pattern: /admin/dashboard/crearlibro
    defaults: { _controller: GensBundle:Admin:crearLibro }

editar_libro:
    pattern: /admin/dashboard/editarlibro/{libro}
    defaults: { _controller: GensBundle:Admin:editarLibro }

#Rutas para redirecciones

_editar_libro:
    pattern: /admin/dashboard/editarlibro/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: editar_libro }

admin_redirect:
    pattern: /admin
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: dashboard }

