gens_homepage:
    pattern:  /
    defaults: { _controller: GensBundle:Default:index }

gens_libro:
    pattern:  /display/{libro}/
    defaults: { _controller: GensBundle:Default:showlibro }

gens_capitulo:
    pattern:  /display/{libro}/{capitulo}
    defaults: { _controller: GensBundle:Default:showcapitulo }
    requirements:
        capitulo:  \d+

admin_redirect:
    pattern: /admin/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: dashboard }

dashboard:
    pattern: /admin/dashboard
    defaults: { _controller: GensBundle:Admin:dashboard }

