gens_homepage:
    pattern:  /
    defaults: { _controller: GensBundle:Default:index }

gens_libro:
    pattern:  /display/{libro}/
    defaults: { _controller: GensBundle:Default:showlibro }

gens_capitulo:
    pattern:  /display/{libro}/{capitulo}
    defaults: { _controller: GensBundle:Default:showcapitulo }
    requirements:
        capitulo:  \d+
